service: birds-of-britsh-empire-pipeline

frameworkVersion: "2 || 3"
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-offline
  - serverless-lift
  - serverless-step-functions

custom:
  bucket: ${env:AWS_S3_BUCKET}
  findBirdNameService: "birds-of-britsh-empire-pipeline"
  createBirdDescriptionService: "birds-of-britsh-empire-pipeline"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  publisher:
    handler: handler.publisher
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
      - http:
          method: post
          path: publisher

stepFunctions: ${file(step-functions.yml)}
