service: create-bird-description

frameworkVersion: "2 || 3"
useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}

functions:
  create-bird-description:
    handler: handler.main
