service: birds-of-britsh-empire-pipeline # NOTE: update this with your service name

frameworkVersion: "2 || 3"
useDotenv: true

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello-world
          method: get
          cors: true
