service: birds-of-britsh-empire-pipeline # NOTE: update this with your service name

frameworkVersion: "2 || 3"
useDotenv: true

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-offline

custom:
  bucket: ${env:AWS_S3_BUCKET}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
