service: cleanup-text

frameworkVersion: "2 || 3"
useDotenv: true

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}

functions:
  numpy:
    handler: handler.main
