service: cleanup-text

frameworkVersion: "2 || 3"
useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-offline

custom:
  externalFunctionName: "birds-of-britsh-empire-pipeline"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:InvokeFunction"
      Resource: arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:custom.externalFunctionName}-${sls:stage}-jobsWorker

functions:
  cleanup-text:
    handler: handler.main
    events:
      - httpApi:
          method: post
          path: /cleanup-text
