name: Deploy AWS Lambda Function

on:
  push:
    branches: [feature/step-functions, main]
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm and modules
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.26.1
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install deps
        run: pnpm i

      - name: Create env file
        run: |
          cat << EOF > .env
          AWS_REGION=${{ secrets.AWS_REGION }}
          AWS_MESSAGE_GROUP=${{ secrets.AWS_MESSAGE_GROUP }}
          AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
          EOF

      - name: Copy .env file to packages
        run: find packages/create-bird-description packages/data-flow-manager packages/find-bird-name -type d -exec cp .env {} \;

      - name: Install serverless globally
        run: pnpm add serverless --global

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy all microservices
        run: pnpm m run deploy
