# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
      with:
      # Created the Secrets Under the Repo only with These Variables
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} #--> Define Region of the AWS-CLI
    - name: Install dependencies
      run: npm ci 
    - name: Deploy zip file to AWS
      run: |
        zip -j deploy.zip ./* #--> Zip the Code As we know lambda function accept the zip file.
        aws lambda update-function-code --function-name=addMessageToQueue --zip-file=fileb://deploy.zip 
      # At last the AWS CLI command to Update the Zip file with existing One (With Correct Function Name)
